name: Day1 Hello
on: push
jobs: 
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: ST1
        run: echo "Hello DevOpsMaster-Nikhil your Github actions run successfully 1"

      - name: ST2
        run: echo "Whos is Master ${{ secrets.MY_DEMO_SECRET }} "
